pipeline {
    agent any

    tools {
        jdk 'MyJdk'
        maven 'Maven3'
    }

    stages {

        stage('Checkout') {
            steps {
                echo 'Checking out source code'
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo 'Building the project'
                dir('CalcDemo') {
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests'
                dir('CalcDemo') {
                    bat 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                echo 'Packaging application'
                dir('CalcDemo') {
                    bat 'mvn package'
                }
            }
        }
    }

    post {
        success {
            echo 'Build completed successfully'
        }
        failure {
            echo ' Build failed'
        }
    }
}
